### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by pandawynn** [guoyang9/AdaVQA#1]
Thanks for your excellent work! I'm a little confused about how to get the 2-D embedding features of the answers, i.e., the results in Figure 1 in the original paper. Would you mind sharing the code for the visualization part?

**Comment by guoyang9** [comment]
The repo is too old, and even I cannot read the code...
But I can offer you some insights if you're interested.

- Two important tools: `Matplotlib `and `T-SNE` (dimension reduction to 2D).

- The data points are from the validation set, where each point corresponds to the outputted feature of the last layer of the network (then use T-SNE to reduce dimension).

- The scatter plot is quite simple, I guess you are more interested in the one lying on a circle. In fact, this one is also easy to obtain. After you have the 2D feature, simply normalize it to a unit vector (so that x*2 + y*2 = 1, and the point is mapped to a circle).

**Comment by pandawynn** [comment]
> The repo is too old, and even I cannot read the code... But I can offer you some insights if you're interested.
> 
> * Two important tools: `Matplotlib `and `T-SNE` (dimension reduction to 2D).
> * The data points are from the validation set, where each point corresponds to the outputted feature of the last layer of the network (then use T-SNE to reduce dimension).
> * The scatter plot is quite simple, I guess you are more interested in the one lying on a circle. In fact, this one is also easy to obtain. After you have the 2D feature, simply normalize it to a unit vector (so that x_2 + y_2 = 1, and the point is mapped to a circle).

I got it. Thanks for your reply.
